### ISSUE TITLE
v13 bulkSave typescript error

### ISSUE THREAD

**Issue by ymshenyu** [typegoose/typegoose#1034]
```ts
error TS2345: Argument of type 'DocumentType<User>[]' is not assignable to parameter of type '(Document<unknown, BeAnObject, User, DefaultIdVirtual, DefaultSchemaOptions> & Omit<User & Required<{ _id: ObjectId; }> & { ...; }, "id" | "typegooseName"> & DefaultIdVirtual & IObjectWithTypegooseFunction)[]'.
  Type 'DocumentType<User>' is not assignable to type 'Document<unknown, BeAnObject, User, DefaultIdVirtual, DefaultSchemaOptions> & Omit<User & Required<{ _id: ObjectId; }> & { ...; }, "id" | "typegooseName"> & DefaultIdVirtual & IObjectWithTypegooseFunction'.
    Property 'id' is missing in type 'Document<unknown, BeAnObject, User, DefaultIdVirtual, {}> & User & Required<{ _id: ObjectId; }> & { __v: number; } & IObjectWithTypegooseFunction' but required in type 'DefaultIdVirtual'.
```

## Versions

- System: windows
- NodeJS: 24.14.0
- Typescript: 5.9.3

- Compiler / Transpiler: tsc
- Typegoose(NPM): 13.2.0 
- mongoose: 9.2.3 
- mongodb: 7.0.0

## What is the Problem?
Typescript compile error when upgrading to v13 and mongoose v9

## Code Example

```ts
import { DocumentType, getModelForClass, prop } from "@typegoose/typegoose";

class Foo {
  @prop()
  name: string;
}

const FooModel = getModelForClass(Foo);

const foo: DocumentType<Foo> = new FooModel({
  name: "test",
});

// Typescript error when using DocumentType<T>
await FooModel.bulkSave([foo]);
```

## Do you know *why* it happens?

Maybe related to [#5f56fb9](https://github.com/typegoose/typegoose/commit/5f56fb98f2a1be43753c7c466fda061b1277ac1c)

---
